default:
  image:
    name: quay.io/pypa/manylinux_2_24_x86_64
    entrypoint: [""]

stages:
  - build
  - test
  - test_predeploy
  - deploy

build:
  stage: build
  script:
    - tools/bazel --bazelrc=.gitlab/ci.bazelrc build //... --build_tag_filters=-needs-models

deploy:
  stage: deploy
  environment:
    name: production
    kubernetes:
      namespace: default
  only:
    - master
  before_script:
    - mkdir -p $HOME/.docker
    - cat $DOCKER_CONFIG_JSON > $HOME/.docker/config.json
    - curl -L https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl -o /usr/bin/kubectl
    - chmod a+x /usr/bin/kubectl
  script:
    - tools/bazel --bazelrc=.gitlab/ci.bazelrc run //k8s:prod.apply

test:
  stage: test
  script:
    - tools/bazel --bazelrc=.gitlab/ci.bazelrc test --test_tag_filters=-needs-models --build_tag_filters=-needs-models -- ... -//:pip_compile_test
  artifacts:
    when: always
    reports:
      junit: bazel-testlogs/**/*.xml

test_predeploy:
  stage: test
  only:
    - master
  before_script:
    - chmod a+x fetch_models.sh
    - ./fetch_models.sh test
  script:
    - tools/bazel --bazelrc=.gitlab/ci.bazelrc test  -- ... -//:pip_compile_test
  artifacts:
    when: always
    reports:
      junit: bazel-testlogs/**/*.xml

