default:
  image:
    # gcc:9-buster 
    name: gcc@sha256:f7a6e098b77a363b2ac86d36c09e7464839e8ac5d99545f4cf899a8e2b90e3c2
    entrypoint: [""]
  cache:
    paths:
      - bazel-output_base
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - tools/bazel --output_base=bazel-output_base build //...

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - mkdir -p $HOME/.docker
    - cat $DOCKER_CONFIG_JSON > $HOME/.docker/config.json
  script:
    - tools/bazel --output_base=bazel-output_base run //k8s:prod.apply

# There are no tests, so this would fail :)
# test:
#   stage: test
#   script:
#     - tools/bazel --output_base=bazel-output_base test //...
