apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiro-tts-deployment
  labels:
    app: tiro-tts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tiro-tts
  template:
    metadata:
      labels:
        app: tiro-tts
    spec:
      volumes:
      - name: models
        emptyDir: {}
      - name: gcs-creds
        secret:
          secretName: gcs-read-service-account-secret
      initContainers:
      - name: fetch-models
        image: google/cloud-sdk:latest
        command:
        - bash
        - -xeu
        - -c
        - |
          {{FETCH_MODELS_SCRIPT}}
        - fetch
        - dep
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: false
        - name: gcs-creds
          mountPath: /creds
          readOnly: true
      containers:
      - name: tts-frontend-service
        image: eu.gcr.io/talgreining-is/tts-frontend-service:git05add43
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: tiro-tts
        image: tiro-tts
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
        env:
        - name: TIRO_TTS_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dev-aws-secret
              key: aws_access_key_id
        - name: TIRO_TTS_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dev-aws-secret
              key: aws_secret_access_key
        - name: TIRO_TTS_SYNTHESIS_SET_PB
          value: conf/synthesis_set.pbtxt
