apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tiro-tts-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: $(INGRESS_HOST)
    http:
      paths:
      - path: /
        backend:
          serviceName: tiro-tts-svc
          servicePort: http
